# Generated by Django 4.0.1 on 2022-01-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_group_name_group_users_movement_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='relations',
        ),
        migrations.AddField(
            model_name='profile',
            name='relations',
            field=models.ManyToManyField(to='api.Relation'),
        ),
    ]
